[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

# Environment variables for the application
[build.environment]
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false"
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"
DB_NAME = "emotech_quiz"

# Railway-specific configurations
[railway]
projectId = "your-project-id"
serviceId = "your-service-id" 